---
label: Theme configuration
hide_body: true
fields:
- type: text
  name: site_name
  label: Site name
- type: textarea
  name: site_description
  label: Site description
- type: textarea
  name: hero_title
  label: Hero title
  config:
    wysiwyg: true
    schema:
      format: html
- type: textarea
  name: hero_subtitle
  label: Hero subtitle
  config:
    wysiwyg: true
    schema:
      format: html
- name: footer
  label: Footer text
  type: text
  hidden: false
  default: ''
- name: header-links
  type: field_group_list
  fields:
  - name: url
    type: text
    config:
      required: false
    label: url
  - name: label
    type: text
    config:
      required: false
    label: label
  config:
    min: 
    max: 
    labelField: 
  label: header-links
  description: Links on header
pages:
- data/theme.json
